---
- hosts: zsystem
  gather_facts: no

  tasks:
    - name: Generate an OpenSSH keypair with the default values (4096 bits, rsa)
      community.crypto.openssh_keypair:
        path: /tmp/id_ssh_rsa
      register: keypair_result
    - debug:
        var: keypair_result